# Travis example for Identifier created by Rafael Garibotti

sudo: false
language: c
compiler:
  - gccvdfbh
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
before_install:
  - sudo apt-get install rbenv
  - sudo apt-get install cppcheck
  - sudo apt-get install valgrind
install:
  - "[ $GCC = gcc ] && export GCC=gcc || true"

script:
  - make
  - make cov
  - make check
  - make valgrind
  - make address
#  - make test
